on: [push]

jobs:
  kryptowire_analysis_job:
    runs-on: ubuntu-latest
    name: Submit app to Kryptowire Portal
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/kryptowire-analysis-action@v2
        with:
          who-to-greet: "Mona the Octocat"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
